
export const layouts = [
  'Album Cover',    'Anatomical Drawing',    'Anatomy',    'Book Cover',

'Brand Identity',    'Business Card',
    'Character Design',
'Character Design Multiple Poses',    'Character Sheet',
'Chart Design',    'Color Palette',
'Coloring Book',    'Comic Strips',
'Doll House',    'Enamel Pin',
'Encyclopedia Page',    'Fashion Moodboard',
'Flat Lay Photography',    'Flyer',    'Full Body Character Design',
'Game Assets',    'Game UI',
'House Cutaway',    'House Plan',
'Icon Set Design',    'Ikea Guide',
'Illustration Split Circle Four Seasons',    'Infographic',
'Interior Design',    'Jewelry Design',
'Knolling',    'Logo Design',
'Magazine Cover',    'Menu Design',
'Mobile App UI Design',    'Nail Art',
'Newsletter Design',    'Outfit',
'Packaging Design',    'Popup Book',    'Postage Stamp',    'Poster',    'Propaganda Poster',
'Reference Sheet',    'Schematic Diagram',
'Seamless Pattern',    'Sticker',    'Story Board',
'T Shirt Vector',    'Tarot Card',
'Tattoo Design',
'Wall Painting',
'Wedding Invitation',
  'Branding Guidelines',  
'Label Design', 'Mood Board',
'Social Media Banner',
'Storybook Illustration', 'Technical Drawing',  
'Label Design',  'Mood Board',
 'Podcast Cover', 'Product Mockup', 'Restaurant Menu', 'Social Media Banner',
'Storybook Illustration', 'Technical Drawing', 'Trade Show Booth Design', 'Web Banner', 'Website Design',
'Wedding Program', 'Zine Layout', 'Art Installation', 'Billboard Design', 'Brochure Design', 'Catalog Design',
'Dashboard Design', 'Data Visualization', 'E-book Layout', 'Food Menu Design', 'Magazine Spread', 'Packaging Box',
'Photo Book', 'Product Catalog', 'Sales Presentation', 'Slideshow Design', 'Typography Poster', 'User Interface Design',
'Vehicle Wrap Design', 'Wallpaper Design', 'Wireframe Layout', 'Yearbook Design',
'Art Print', 'Backdrop Design',  'Certificate Design', 'Class Schedule', 'CV/Resume Design',
'Event Poster', 'Greeting Card', 'Label Design', 'Letterhead Design', 'Manga Page', 'Mood Board',
'Packaging Label', 'Photo Collage',
    
  ];

  export const social = [
    "YouTube Thumbnail",
    "Instagram Story",
    "Facebook Live Video",
    "Twitter Poll",
    "LinkedIn Article",
    "TikTok Dance",
    "Snapchat Geofilter",
    "Pinterest Pin",
    "Reddit AMA (Ask Me Anything)",
    "Tumblr GIF Set"
]


  export const textures = [
    '3d Fractals',
    'Agate',
    'Aluminum',
    'Amber',
    'Amethyst',
    'weight',
    'Amigurumi',    'Ammolite',
    'Anodized',    'Anodized Titanium',
    'Awning Stripe',
    'Basalt',    'Brass',
    'Breton Stripes Pattern',    'Brick',
    'Bronze',
    'Brushed Aluminum',    'Bumpy',    'Candy Stripes',    'Celtic Knot',    'Ceramic',
    'Chain Pattern',    'Chainmail',    'Chalk Stripes',    'Checks Pattern',
    'Cheetah Print Pattern',    'Cherry Wood',    'Chevron Pattern',    'Chinoiserie',
    'Citrine',    'Clay',    'Cloisonne',    'Coal',    'Coarse',
    'Cobblestone',    'Concrete',    'Corundum',   'Cotton',
    'Crossstitch',    'Dalmatian Pattern',    'Damascus Titanium',    'Damask Pattern',
    'Denim',    'Embers',    'Embroidered',    'Emerald',
    'Eopart Print',    'Epoxy',    'Fabric',    'Filigree',    'Fingerprint Pattern',    'Fire',
    'Floral Texture',    'Fluffy',    'Fluid',    'Foil',    'Fractal',
    'Furry',    'Gingham',    'Girih',
    'Glen Check Pattern',    'Glossy',
    'Gold',    'Gritty',
    'Hairy',    'Herringbone Pattern',
    'Hexagon',
    'Holographic',    'Icy',    'Iridescent',
    'Ironwork',    'Ivory Carving',
    'Jade',    'Jasper',    'Jelly',    'Kaleidoscopic Pattern',
    'Khokhloma',    'Knitting Pattern',
    'Kyanite',    'Lace',    'Lacquer',    'Lapis',
    'Leather',    'Light Particles',    'Linguini Pattern',    'Liquid Bismuth',
    'Liquid Gold',    'Liquid Metal',
    'Magma',    'Malachite',    'Mandelbulb',
    'Marble',    'Matte',
    'Mesh',    'Mesh Wire',
    'Moldy',    'Molten',
    'Mosaic',    'Nailshead',
    'Nickel',    'Oak Wood',
    'Onyx',    'Opal',
    'Ornate',
    'Paisley',
    'Paper',
    'Pasta Pattern',
    'Peridot',    'Pinstripes',    'Plaid',
    'Planks',    'Platinum',    'Polka Dot',
    'Prickly',    'Quartz',    'Rainbow Marble',
    'Rose Gold',    'Rubber Band',
    'Sand Texture',    'Sandpaper',    'Sapphire',
    'Sequin',    'Serpentine Stripes Pattern',
    'Shark Skin',    'Shepherds Check',
    'Spinel',    'Stained Glass',
    'Stone',    'Stone Brick Texture',
    'Straw',    'Stucco',    'Tartan',    'Terrazzo',    'Tinsel',    'Tissue Paper',    'Tourmaline',
    'Twill',
    'Variscite',    'Velvety',
    'Voxel',    'Windowpane Pattern',    'Wooden',
    'Wool',
    'Wrinkly',    'Yarn',
    'Zebra Print',    'Acrylic',
    'Bark',    'Bubble Wrap',
    'Burlap',
    'Carbon Fiber',
    'Cork',
    'Cracked Earth',
    'Crocodile Skin',
    'Denim Washed',
    'Diamond Plate',
    'Distressed Metal',
    'Feathers',
    'Fish Scales',
    'Fleece',
    'Geode',
    'Granite',
    'Grass',
    'Hammered Metal',
    'Ice Crystals',
    'Limestone',
    'Linen',
    'Marble Veins',
    'Metal Grid',
    'Moire',
    'Paisley Print',
    'Pine Wood',
    'Rattan',
    'Sand Dunes',
    'Scratched Metal',
    'Silk',
    'Snake Skin',
    'Suede',
    'Tiled',
    'Tweed',
    'Veined Marble',
    'Waffle',
   'Water Droplets',
    'Wavy Lines',
    'Weave Pattern',
    'Zellige Tiles',
  ]
  export const colorArray = ["Apricot Color", "Aqua Colors", "Ash Gray", 
  "Auburn Color", "Baby Blue", "Baby Pink", "Beige Colors", "Black", 
  "Black Bean Color", "Black Olive", "Blonde", "Blood Red", "Blue Violet", 
  "Blush Colors", "Bordo Color", "Bright Bold Colors", "Bronze Colors", "Brunette", 
  "Buff Color", "Burgundy Colors", "Burnt Amber", "Burnt Sienna", "Canary Yellow", 
  "Candy Colors", "Cerulean Blue Color", "Chartreuse Color", "Chestnut Color", 
  "Chinese Violet", "Cinnamon Colors", "Cobalt Blue Color", "Cold Colors", 
  "Cool Colors", "Cooper Color", "Coral Color", "Cornflower Blue", "Cotton Candy Colors", 
  "Crimson Colors", "Cyan Colors", "Danish Pastel Colors", "Dark Green", "Dark Orange",
   "Dark Pink", "Dark Pink Colors", "Dark Purple", "Dark Red", "Dark Vibrant Colors", 
   "Dark Violet", "Desaturated", "Ecru Color", "Electric Blue", "Electric Colors", 
   "Electric Indigo", "Electric Purple", "Fflax Color", "Forest Green", "Frost Colors", 
   "Fuchsia Colors", "Golden Yellow", "Gradient Colors", "Graph Color", "Gummy Colors", 
   "Gunmetal Gray", "Hot Colors", "Hot Pink", "Hunter Green", "Indigo", "Ivory", 
   "Kelly Green", "Khaki Colors", "Lavender Blush", "Lemon Yellow", "Light Green", 
   "Light Pink Colors", "Lime Colors", "Linen Color", "Magenta Color", "Mahogany Color", 
   "Marigold Color", "Maroon", "Mauve", "Midnight Blue", "Millenial Pink", "Mint Color", 
   "Mocha", "Muted Colors", "Navajo White", "Navy Blue", "Neon Colors", "Neon Green", 
   "Neon Orange", "Neon Pink", "Neutral Colors", "Olive Color", "Orange", "Orange Red", 
   "Pastel Green", "Pastel Orange", "Pastel Pink", 

  "Peach Color", "Persimmon Color","Platinum Color",
"Plum Colors",
"Prussian Blue",
"Raisin Color",
"Red",
"Red Copper",
"Retro Colors",
"Rich Colors",
"Rouge Color",
"Royal Blue",
"Russian Violet",
"Rustic Colors",
"Saffron Yellow",
"Salmon Color",
"Scarlet Color",
"Sepia Colors",
"Sienna Color",
"Silver Colors",
"Sky Blue Color",
"Slate Gray",
"Smoky Black",
"Snow White",
"Spectrum Colors",
"Spring Green",
"Sweet Colors",
"Tan Color",
"Tangerine Color",
"Taupe",
"Tawny Color",
"Tea Color",
"Teal",
"Technicolor",
"Tropical Colors",
"True Blue",
"Turquoise Color",
"Vantablack","Vibrant Colors",
"Vibrant Holographic Gradient","Vintage Colors","Violet","Warm Colors","Watermelon Color","White","Yellow Green"]

export const artists = [    'Ivan Shishkin',    'Zdzislaw Beksinski',    'James Gurney',    'Claude Lorrain',    'Edward Hopper',
    'Adolph Menzel',
    'Alexei Savrasov',    'Andrew Wyeth',
    'Vilhelm Hammershoi',    'Salvador Dali',    'Pablo Picasso',    'Andre Masson',    'Max Ernst',    'Rene Magritte',    'Jim Burns',
    'Vincent Di Fate',    'Jean Delville',
    'Wassily Kandinsky',    'Marcia Santore',    'Kandinksey',    'Paul Cezane',
    'Lawrence Pelton',    'Amanda Sage',    'Amedeo Modigliani',    'Henry Moore',
    'Van Gogh',    'Wes Anderson',    'Alphonso Mucha',    'Gustav Klimt',
    'Albert Bierstadt',    'Thomas Kinkade',    'Affadi',
    'Alexej Von Jawlensky',    'Alice Neel',    'Alyssa Monks',    'Alfred Kubin',    'David Alabo',    'Anne Stokes',    'Gerald Brom',
    'Grant Wood',    'Albrecht Durer',    'Alex Grey',    'Dan Mumford',    'Andy Warhol',    'David Hockney',
    'Lisa Frank',    'Marc Simonetti',    'Alan Lee',    'John Constable',    'Leonardo Da Vinci',
    'Da Vinci',    'Hieronymus Bosch',    'Canaletto',
    'Annibale Carracci',    'Anthony Van Dyck',    'Robert Rauschenberg',
    'Man Ray',    'Morton Livingston Schamberg',
    'Marcel Duchamp',    'Suzanne Duchamp',    'Francis Picabia',
    'Georges Ribemont-Dessaignes',    'Juliette Roche',    'Wilhelm Fick',    'George Grosz',    'Hannah Hoch',
    'Kurt Schwitters',    'Julius Evola',    'Serge Charchoune',    'Ilia Zdanevich',
    'Jean Crotti',    'Sophie Taeuber-Arp',    'Genpei Akasegawa',    'Josip Demirovic Devj',
    'Jim Dine',    'Arthur Kopcke',    'George Maciunas',    'Valery Oisteanu',
    'Ushio Shinohara',    'Jean Tinguely',    'Masunobu Yoshimura',
    'Mr. Brainwash',    'Thierry Guetta',    'Seen',    'Richard Mirando',
    'Futura',    'Leonard Hilton McGurr',    'Os Gemeos',    'Tristan Eaton',
    'Banksy',    'Eduardo Kobra',    'Swoon',    'Caledonia Curry',    'Artur Bordalo',
    'Invader',    'Anthony Lister',    'Uon.visuals',    'Seth McMahon',    'Artofethan',    'Peter Mohrbacher',    'Boris Groh',    'Annton Fadeev',    'Alena Aenami',    'Andreas Rocha',
    'Aleksi Briclot',
    'Ivan Stan',    'Junji Ito',
   
  
]

export const camera = [
  "Photography", "Photograph", "Photographia",
  "Closed Composition",
  "Filmic", "Film Noir Style", "Cinematic",
  "Dramatic", "Glamor Shot",
  "Golden Hour", "Blue Hour",
  "Award Winning Photography", "Establishing Shot", "Nightography",
  "Product Photography",
  "Photoshoot",
  "Portrait", "Full Body Portrait", "Portraiture",
  "Subject",
  "Pose", "Gesture", "Profile",
  "Cinematic Haze",
  "High-Speed Photograph", "Time-Lapse", "Motion Capture",
  "Claymation", "Video Frame Capture",
  "Stop Motion", "Stop-Motion Animation Frame",
  "Color Grading", "Bokeh", "Film Grain",
  "Surveillance", "Surveillance Footage",
  "Security Footage", "CCTV",
  "Dashcam-Footage", "Satellite Imagery", "Paparazzi Photography",
  "Underwater Photography", "Wildlife Photography", "National Geographic Photo",
  "Editorial Photography", "Associated Press Photo", "Photojournalism",
  "Action Scene", "War Photography",
  "Camera and Film Types",
  "Camcorder Effect", "DSLR", "Night Vision",
  "Drone Photography", "GoPro Video", "Unregistered Hypercam 2",
  "Hyperspectral Imaging", "Multispectral Imaging", "Schlieren",
  "Disposable Camera", "Disposable Camera Photo",
  "Polaroid",
  "Ektachrome", "Fujifilm Superia", "Instax",
  "Kodak Ektar", "Kodak Gold 200", "Kodak Portra",
  "Nikon D750", "Provia", "Velvia",
  "Lomo", "Pinhole Photography", "CinemaScope",
  "Tri-X 400 TX", "Ilford HP5", "Photogram",
  "VistaVision", "Technirama",
  "Techniscope", "Super-35",
  "Panavision", "Super-Panavision-70",
  "Cinerama", "Kinopanorama", "Cinemiracle",
  "Daguerrotype", "Ambrotype", "Calotype",
  "Tintype", "Film-Negative",
  "Full Frame",
  "Film Sizes",
  "Shot on 8mm", "Shot on 9.5mm",
  "Shot on 16mm", "Shot on 17.5mm", "Shot on 28mm",
  "Shot on 35mm", "35mm", "Expired 35mm Film",
  "Shot on 65mm", "Expired 65mm Film",
  "Shot on 70mm", "Shot on IMAX 70mm",
  "Lens Sizes",
  "15mm Lens", "35mm Lens", "85mm Lens",
  "100mm Lens", "200mm Lens",
  "Lenses",
  "Macro", "Macro View", "Magnification",
  "100x Magnification", "200x Magnification",
  "500x Magnification", "1000x Magnification",
  "Microscopic", "Electron Microscope", "Super-Resolution Microscopy",
  "Telescope", "Telescopic", "Telescope Photography",
  "Telephoto", "Panorama", "360 Panorama",
  "Wide Angle", "Ultra-Wide Angle", "360 Angle",
  "Shift-L"
]

export const objects = [
  // Fruit and Vegetable
  'Fig', 'Mango', 'Cauliflower',

  // Meats, Cheeses, and Eggs
  'Beef', 'Wagyu', 'Tallow',
  'Pork', 'Bacon',
  'Cheese',
  'Egg', 'Egg Yolk',

  // Bread
  'Bread', 'Made of Bread', 'Pretzel',
  'Shortcrust-Pastry', 'Flaky-Pastry', 'Puff-Pastry',
  'Choux-Pastry', 'Phyllo',

  // Nuts and Beans
  'Beans',
  'Peanut',
  'Coconut',

  // Dishes and Meals
  'Pizza', 'Hotdog',
  'Pasta', 'Spaghetti', 'Fettuccine',
  'Gnocchi',
  'Macaroni and Cheese',

  // Sauces, Spreads, and Oils
  'Vegetable Oil', 'Olive Oil',
  'Butter', 'Margarine',
  'Peanut Butter', 'Jelly',
  'Alfredo',
  'Sour Cream', 'Sauce', 'Pasta Sauce',
  'Ketchup', 'Mustard',
  'Mayonnaise', 'Mayo',

  // Herbs and Spices
  'Cinnamon',

  // Candy and Sweets
  'Cake', 'Wedding Cake', 'Cake Decorating',
  'Brownies',
  'Churros', 'Syrup', 'Maple Syrup',
  'Cream', 'Whipped Cream', 'Ice Cream',
  'Candy', 'Lollipop', 'Taffy',
  'Cotton-Candy', 'Candy-Floss',
  'Gummy Candy', 'Gummies',
  'Chocolate', 'Caramel',
  'Marzipan', 'Gum Paste', 'Modeling Chocolate',
  'Sprinkles', 'Nonpareils',
  'Fondant Icing', 'Royal Icing',
  'Honeycomb', 'Creme Brule',
  'Eclair', 'Cannoli', 'Fruit-Tart',
  'Gumdrop', 'Gum',
  'Dessertwave',

  // Beverages
  'Soda', 'Coffee', 'Tea',
  'Wine', 'White-Wine', 'Red-Wine',
  'Champagne',
  'Corona', 'Corona-Phenomenon',

  // Other Food and Consumables
  'Food',
  'Macaroni',
  'Gelatin', 'Agar',
  'Edible Ink', 'Food Coloring', 'Food Dye',
  'Deep-Fried', 'Molecular Gastronomy',
  'Tincture',
  'Toothpaste',

  // Microscopic Objects
  'Atom', 'Fullerene', 'Nanoparticle',
  'Cells', 'Cellular',
  'Mitochondria', 'Mitosis',
  'DNA', 'Bacteria', 'Enzyme',

  // Digital Objects
  'Computer', 'Display',
  'Camera', 'Lens', 'Film',
  'Vinyl Record', 'CD',
  'DVD', 'Blu-Ray Disc',
  'Videocasette',
  'Capacitance Electronic Disc', 'LaserDisc', 'Holographic Versatile Disc',
  'Transistor', 'Diode',
  'Wires', 'Cables',
  'Flux Capacitor',
  'Clock',   // Digital Objects
  'Digital-Clock',
  'Wristwatch',

  // Toys
  'Toy',
  'Pinwheel', 'Slinky', 'Newtons-Cradle',
  'Jigsaw', 'Puzzle', 'Tangram',
  'Maze',
  'Stress Ball', 'Koosh Ball', 'Koosh',
  'Beach-Ball', 'Ball Pit', 'Zorb',
  'Rubik\'s Cube', 'Kinetic-Sand',
  'Cards', 'Dominoes', 'Marbles',
  'Chess', 'Pogs',
  'Lego', 'Lego-Mindstorms', 'Lego-Mindstorms-NXT',
  'Lincoln-Logs', 'Megablocks',
  'Etch-A-Sketch', 'Lite-Brite',

  // Clothing
  'Uniform', 'Outfit', 'Wearable',
  'Jeans',
  'Tuxedo', 'Polo', 'Fedora',
  'Dress', 'Dressed',
  'Shoe', 'Shoes', 'Hat',
  'Glasses', 'Wearing Glasses',
  'Sunglasses', 'Wearing Sunglasses',
  'Necktie', 'Bow Tie', 'Bowtie',
  'Jumpsuit',

  // Instruments
  'Instrument',
  'Piano', 'Accordion', 'Saxophone',

  // Vehicles
  'Car', 'Airplane', 'Rocket Ship',
  'Blimp', 'Hot Air Balloon',
  'Auto',

  // Good Luck Charms
  'Charm', 'Good-Luck-Charm',
  'Horseshoe', 'Amulet', 'Dreamcatcher',

  // Badges, Patches, and Trophies
  'Badge', 'Heraldic Badge',
  'Trophy', 'Gorget Patch',

  // Ambiguous Objects
  'Object',
  'Stuff', 'Things', 'Items',
  'Trinket', 'Knickknack', 'Nick-Nack',
  'Bauble', 'Curio', 'Tchotchke',
  'Doodad', 'Blobject',

  // Other Objects
  'Dichroic-Prism', 'Dispersive-Prism', 'Bubble',
  'Seashell', 'Toilet', 'Bean-Bag',
  'Cage', 'Cheese Grater',
  'Bracelet', 'Ribbons', 'Fingerprint',
  'Bling',
  'Tesla Valve',
  'Flag', 'Bench', 'Yardstick',
  'Backdrop', 'Greenscreen',
  'Veins',
  'Bunsen Burner',
  'Needle', 'Screw',
  'Nail', 'Metal Nail',
  'Paper Clips',
  'Band-Aid', 'Bandage', 'Gauze',
  'Rubber Band', 'Rubber Band Ball', 'Silly Band',
  'Balloon',
  'Soap', 'Lipstick',
  'Plume',
  'Mat',
  'Teapot'
]

export const styles = [
  '3d',
  'Abstract Art',
  'Abstract Expressionism',
  'Abstract Illusion',
  'Action Painting',
  'Alebrijes',
  'Analytical Cubism',
  'Art Brut',
  'Art Deco',
  'Art Nouveau',
  'Arte Povera',
  'Automatism',
  'Bauhaus',
  'Bayeux Tapestry',
  'Britpop',
  'Bronze Age',
  'Brutalism',
  'Bubble Goth',
  'Caricature',
  'Cartographic Art',
  'Cartoon',
  'Childrens Book Illustration',
  'Cinematic',
  'Cloisonnism',
  'Collage Art',
  'Color Field Painting',
  'Colorful Collages',
  'Comic',
  'Commercial Art',
  'Conceptual Art',
  'Concretism',
  'Constructivism',
  'Coptic Art',
  'Cubism',
  'Cubo Expressionism',
  'Cubo Futurism',
  'Cyberdelic',
  'Dada',
  'Dbz Style',
  'De Stijl',
  'Digital Art',
  'Digital Painting',
  'Disney',
  'Documentary Photography',
  'Dynamic Pose',
  'Dystopian Art',
  'Electrifying Art',
  'Expressionism',
  'Fauvism',
  'Fiber Art',
  'Figurative Expressionism',
  'Fine Art Photography',
  'Fisheye',
  'Flat Design',
  'Folk Art',
  'Funkypop',
  'Geometric',
  'Geometric Abstraction',
  'Geometric Painting',
  'Ghibli',
  'Gibson Girl',
  'Graffiti Art',
  'Grunge',
  'Hyper Realism',
  'Hypermaximalistic',
  'Hyperrealistic',
  'Hyperrealistic Anime',
  'Illustration',
  'Impressionism',
  'Intimism',
  'Intricate Maximalist',
  'Isometric',
  'Japonisme',
  'Junglecore',
  'Kawaii',
  'Kinetic Art',
  'Levitation',
  'Light And Space',
  'Light Art',
  'Lofi Art',
  'Low Poly',
  'Luminism',
  'Lyrical Abstraction',
  'Mail Art',
  'Manga',
  'Manhua',
  'Manhwa',
  'Marvel',
  'Maximalism',
  'Mechanistic Cubism',
  'Memphis Design',
  'Miniaturecore',
  'Minimalism',
  'Naive Art',
  'Neo Dada',
  'Neo Expressionism',
  'Neo Geo',
  'Neo Impressionism',
  'Neo Minimalism',
  'Neo Suprematism',
  'Neoplasticism',
  'Octane Render',
  'Op Art',
  'Orphism',
  'Outsider Art',
  'Overlay Art',
  'Pattern And Decoration',
  'Perception Art',
  'Photorealistism',
  'Pictorialism',
  'Pixar',
  'Popart',
  'Post Impressionis',
  'Post Minimalism',
  'Post Painterly Abstraction',
  'Postminimalism',
  'Precisionism',
  'Primitivism',
  'Psychedelia',
  'Psychedelic',
  'Pulp Art',
  'Purism',
  'Pysanky',  'Realistic',
  'Rpg Maker',
  'Sanrio',
  'Spatialism',
  'Street Art',
  'Street Photography',
  'Sumi E',
  'Superflat',
  'Suprematism',
  'Surrealism',
  'Symmetrical',
  'Synchromism',
  'Synesthesia',
  'Synthetic Cubism',
  'Textile Art',
  'Tonalism',
  'Toyism',
  'Transautomatism',
  'Transavantgarde',
  'Ukiyo E',
  'Unreal Engine',
  'Voronoi',
  'Whimsical',
  'Yinyang',
  'Zynga'
]

export const themes = [
  'Academicism',
  'Acid Pixie',
  'Acidwave',
  'Adventurecore',
  'Afrofuturism',
  'Agropeople',
  'Anachronism',
  'Angelcore',
  'Anthropomorphism',
  'Atompunk',
  'Autumn',
  'Biedermeier',
  'Biophilic Design',
  'Biopunk',
  'Bloomcore',
  'Bohemian',
  'Bronzepunk',
  'Byzantine',
  'Chaotic',
  'Contemporary',
  'Contemporary Realism',
  'Cosmos',
  'Creepy',
  'Crusader',
  'Crustpunk',
  'Cyber Art',
  'Dark Fantasy',
  'Dark Nautical',
  'Decopunk',
  'Dieselpunk',
  'Dreamy',
  'Emo',
  'Environmental Art',
  'Ethereal',
  'Evil Theme',
  'Extraterrestrial',
  'Fairytale',
  'Fantasy Art',
  'Farmcore',
  'Feminist Art',
  'Floral',
  'Flowercore',
  'Futurism',
  'Ghostcore',
  'Goblincore',
  'Gothic',
  'Hallyu',
  'Happycore',
  'Haunting',
  'Hikecore',
  'Horrific',
  'Indian Space Painting',
  'International Gothic',
  'Junk Art',
  'Komnenian Style',
  'Lightcore',
  'Lightningwave',
  'Magic Realism',
  'Magical',
  'Mandala',
  'Mannerism',
  'Metaphysical Art',
  'Miserablism',
  'Modern',
  'Modernismo',
  'Muralism',
  'Mythology',
  'Mythpunk',
  'Native Art',
  'Naturalism',
  'Neo Orthodoxism',
  'Neo Romanticism',
  'New Casualism',
  'Nouveau Realisme',
  'Oni',
  'Orientalism',
  'Otherworldly',
  'Palekh',
  'Paranormal',
  'Prehistoricore',
  'Protopsychology',
  'Ptolemaic',
  'Queer Art',
  'Rain',
  'Rainbowcore',
  'Renaissance',
  'Retro',
  'Retrofuturism',
  'Robotic',
  'Romantic',
  'Romanticism',
  'Rustic',
  'Shpongle',
  'Sky Art',
  'Slimepunk',
  'Socialist Realism',
  'Space Art',
  'Sparklecore',
  'Spring',
  'Steampunk',
  'Synthwave',
  'Tenebrism',
  'Tiki',
  'Tribal Art',
  'Trillwave',
  'Tropical',
  'Unicorncore',
  'Urbancore',
  'Vaporwave',
  'Viking',
  'Weirdcore',
  'Whimsigothic',
  'Witchcore',
  'Wonderland',
  'Zen',
  'Zombie Theme',
  'Zombiepun'
];


const shapesArray = [
  '2D Shape',
  'Point',
  'Dot',
  'Line',
  'Triangle',
  'Chevron',
  'Square',
  'Pentagon',
  'Hexagon',
  'Hexagonal',
  'Heptagon',
  'Octagon',
  'Nonagon',
  'Decagon',
  'Rectangle',
  'Rectangular',
  'Parallelogram',
  'Rhombus',
  'Star',
  'Heart',
  'Spirangle',
  '3D Shape',
  'Orb',
  'Cube',
  'Cuboid',
  'Sphere',
  'Cylinder',
  'Torus',
  'Pyramid',
  'Cone',
  'Rectangular Prism',
  'Star Prism',
  'Wedge',
  'Zonohedron',
  'Tetrahedron',
  'Octahedron',
  'Dodecahedron',
  'Icosahedron',
  'Kepler–Poinsot Polyhedra',
  'Cuboctahedron',
  'Rhombicuboctahedron',
  'Icosidodecahedron',
  'Rhombicosidodecahedron',
  'Trapezohedron',
  'Bezier Surface',
  'Cupola',
  'Anticupola',
  'Hypercupolae',
  'Bicupola',
  'Frustum',
  'Bifrustum',
  'Rotunda',
  'Birotunda',
  'Prismatoid',
  'Scutoid',
  'Bipyramid',
  'Star Bipyramid',
  'Antiprism',
  'Anti-Prism',
  'Trapezohedra',
  'Star Trapezohedron',
  'Spherical Polyhedron',
  'Mobius Strip',
  'Hexaflexagon',
  'Miura Fold',
  '4D Shape',
  'Hyper Shape',
  '4D Hyper Shape',
  'Hyperplane',
  'Hypersurface',
  'Hypercube',
  'Tesseract',
  'Hyperprism',
  'Hypersphere',
  'Hypercylinder',
  'Hypertorus',
  'Hyperpyramid',
  'Hypercone',
  'Klein Bottle',
  'Hyperzonohedron',
  'Hypertetrahedron',
  'Hyperoctahedron',
  'Hyperdodecahedron',
  'Hypericosahedron',
  'Flexible Polyhedron',
  'Monogon',
  'Digon',
  'Geometry',
  'Geometric',
  'Islamic Geometric Patterns',
  'Poly',
  'Polygon',
  'Polygonal',
  'Polyhedron',
  'Polyhedral',
  'Platonic Solids',
  'Archimedean Solids',
  'Catalan Solids',
  'Manifold',
  'Multifold',
  'Maniform',
  'Multiform',
  'Non-Euclidian',
  'Form-Constant',
  'Vertex',
  'Edge',
  'Surface',
  'Interior',
  'Exterior',
  'Anterior',
  'Convex',
  'Concave',  'Convex Hull',
  'Symmetry',
  'Symmetric',
  'Asymmetric',
  'Equiangular',
  'Equilateral',
  'Cyclic',
  'Tangential',
  'Rectilinear',
  'Traverse',
  'Quasi',
  'Quasi-Regular',
  'Topology',
  'Topological',
  'Isogonal',
  'Isotoxal',
  'Isohedral',
  'Stellation',
  'Ehrhart Polynomial',
  'Ideal Polyhedron'
]

export const lighting = [
  "Blacklight",
  "Blue Hour",
  "Bokeh",
  "Chemiluminescence",
  "Cinematic Lighting",
  "Crepuscular Rays",
  "Dappled Light",
  "Disco Lighting",
  "Dramatic Lighting",
  "Dreamy Glow",
  "Dual Lighting",
  "Dusk",
  "Electroluminescent Wire",
  "Electromagnetic Spectrum",
  "Flare",
  "Floodlight",
  "Flourescent Lighting",
  "Frontal Lighting",
  "Glitter",
  "Glow In The Dark",
  "Glowing",
  "Glowing Neon",
  "Glowing Particle Effects",
  "Glowing Radioactively",
  "Gobo",
  "Golden Hour",
  "Hard Lighting",
  "High Key Lighting",
  "Internal Glow",
  "Laser",
  "Lava Glow",
  "Lens Flare",
  "Low Key Lighting",
  "Midnight",
  "Moody Lighting",
  "Moonlight",
  "Neon Lights",
  "Nightclub Lighting",
  "Nuclear Wasted Glow",
  "Prismatic Highlights",
  "Radioluminescence",
  "Rainbow Sparks",
  "Ray Tracing Reflections",
  "Shimmering Lights",
  "Soft Lighting",
  "Starry",
  "Sunlighting",
  "Sunlit",
  "Torchlit",
  "Twilight Hour"
];


export const techniques = [
  "Frontlight",
  "Halfrear Lighting",
  "Backlight",
  "Dim",
  "Dim Lighting",
  "Dark Lighting",
  "Bright",
  "Ultrabright",
  "Blinding Light",
  "Moody Lighting",
  "Mood Lighting",
  "Cinematic Lighting",
  "Studio Lighting",
  "Cove Lighting",
  "Soft Lighting",
  "Hard Lighting",
  "Accent Lighting",
  "Volumetric",
  "Volumetric Lighting",
  "Contre-Jour",
  "Rembrandt Lighting",
  "Split Lighting",
  "Beautiful Lighting",
  "Low-Key Lighting",
  "High-Key Lighting",
  "Downlighting",
  "Uplighting",
  "Under-Illumination",
  "Over-Illumination",
  "Veiling Flare",
  "Caustic Lighting",
  "Ethereal Lighting",
  "Nightclub Lighting",
  "DJ Lighting",
  "Concert Lighting",
  "Museum Lighting",
  "Light Pollution",
  "Epic Light",
  "Spotlight",
  "Floodlight",
  "Rim Lights",
  "Rim Lighting",
  "Marquee",
  "Strobe",
  "Strobe Light",
  "Stroboscope",
  "Flickering Light",
  "Bubble Light",
  "Crepuscular Rays",
  "Rays of Shimmering Light",
  "Godrays",
  "Anticrepuscular Rays",
  "Light Pillars",
  "Tyndall Effect",
  "Afterglow",
  "Airglow",
  "Alpenglow",
  "Artificial Lighting",
  "Natural Lighting",
  "Sunlight",
  "Direct Sunlight",
  "Sunshine Ray",
  "Sunbeams",
  "Sunshaft",
  "Moonbeams",
  "Starlight",
  "Waning Light",
  "Radiant Light",
  "Incandescent",
  "Fluorescent",
  "CFL",
  "CFL Light",
  "Candlelight",
  "Torch",
  "Torch Light",
  "Tesla Coil",
  "Electric Arc",
  "Glow Stick",
  "Blacklight",
  "Gobo",
  "Gobo Light",
  "Halogen",
  "Argon Flash",
  "Lantern",
  "Schwarz Lantern",
  "Coleman Lantern",
  "Flare",
  "Ember Light",
  "Edison Bulb",
  "Nightlight",
  "Christmas Lights",
  "Optical Fiber",
  "Electroluminescent Wire",
  "Electromagnetic Spectrum",
  "Infrared",
  "Ultraviolet",
  "UV",
  "X-Ray",
  "Orbital X-Ray",
  "Lightspeed",
  "Nightclub",
  "Glowing Radioactivity",
  "Nuclear Waste",
  "Glowing Nuclear Waste",
  "Flash-Lamp",
  "Flashtube",
  "Incandescent Lamp",
  "Fluorescent Lamp",
  "Plasma Globe",
  "Plasma Lamp",
  "Lava Lamp",
  "Crackle Tube",
  "Halogen Lamp",
  "Neon Lamp",
  "Xenon Lamp",
  "Krypton Lamp",
  "Argon Lamp",
  "Helium Lamp",
  "Carbide Lamp",
  "Argand Lamp",
  "Diya Lamp",
  "Arc Lamp",
  "Gas Lamp",
  "Gas Mantle",
]

export const architecture = [
  "Antebellum Architecture",
  "Arabic Interior Design",  "Southwestern Interior Design",
  "Spanish Landscape Design",
  "Spanish Revival Architecture",
  "Spanish Revival Interior Design",
  "Sphinx",
  "Splendour Interior Design",
  "Stalinist Architecture",
  "Storybook Architecture",
  "Sustainable Architecture",
  "Transitional Interior Design",
  "Tropical Landscape Design",
  "Tudor Architecture",
  "Tuscan Landscape Design",
  "Victorian Architecture",
  "Victorian Interior Design",
  "Woodland Landscape Design",
  "Zen Architecture",  "Mid-Century Modern Architecture",
  "Mid-Century Modern Interior Design",
  "Scandinavian Mid-Century Design",
  "Danish Modern Design",
  "Eames Era Design",
  "Atomic Ranch Design",
  "Brutalist Architecture",
  "Palm Springs Modern Design",
  "Googie Architecture",
  "Zen Interior Design",
  "Ziggurat",
  "Art Deco Architecture",
  "Art Deco Interior Design",
  "Art Nouveau Architecture",
  "Barbie Interior Design",
  "Baroque Architecture",
  "Bauhaus Interior Design",
  "Bay And Gable Architecture",
  "Beauxarts Architecture",
  "Beauxarts Interior Design",
  "Biophilic Interior Design",
  "Boho Interior Design",
  "Bungalow",
  "Cabin",
  "Carpenter Gothic Architecture",
  "Coastal Interior Design",
  "Colonial Architecture",
  "Contemporary Architecture",
  "Contemporary Interior Design",
  "Cottage",
  "Craftsman Architecture",
  "Creole Cottage Architecture",
  "Cycladic Architecture",
  "Cycladic Interior Design",
  "Danish Interior Design",
  "Dark Academia Interior Design",
  "Deconstructivism Architecture",
  "Directoire Interior Design",
  "Dutch Colonial Architecture",
  "Eclectic Interior Design",
  "Farmhouse",
  "Farmhouse Interior Design",
  "Federal Architecture",
  "Flemish Interior Design",
  "French Country Interior Design",
  "French Garden",
  "Futuristic Interior Design",
  "Garrison Colonial Architecture",
  "Georgian Architecture",
  "Georgian Interior Design",
  "German Colonial Architecture",
  "Googie Architecture",
  "Googie Interior Design",
  "Gothic Architecture",
  "Greek Architecture",
  "Greek Interior Design",
  "Greek Revival Architecture",
  "Greek Revival Interior Design",
  "Homestead",
  "Hypostyle Architecture",
  "Igloo",
  "Indian Architecture",
  "Indian Vibrancy Architecture",
  "Indian Vibrancy Interior Design",
  "Industrial Interior Design",
  "Italiante Exterior Design",
  "Jacobean Interior Design",
  "Japandi Architecture",
  "Japandi Interior Design",
  "Japanese Garden",
  "Lodge",
  "Maximalism Interior Design",
  "Medieval Survivals",
  "Mediterranean Interior Design",
  "Mediterranean Revival Architecture",
  "Midcentry Modern",
  "Minimal Interior Design",
  "Modern Farmhouse Interior Design",
  "Monterey Colonial Architecture",
  "Moorish Architecture",
  "Moorish Interior Design",
  "Moorish Revival Architecture",
  "Moroccan Interior Design",
  "Nautical Interior Design",
  "Neo Electic Architecture",
  "Neo Futuristic Interior Design",
  "Neoclassical Architecture",
  "Neofuturistic Architecture",
  "Neolithic Architecture",
  "Neolithic Interior Design",
  "Obelisk",
  "Otto Wagner Architecture",
  "Otto Wagner Interior Design",
  "Ottoman Architecture",
  "Palladian Architecture",
  "Palladian Interior Design",
  "Parametric Architecture",
  "Parametric Interior Design",
  "Pastel Interior Design",
  "Prairie Landscape Design",
  "Pueblo Architecture",
  "Pueblo Interior Design",
  "Pyramid",
  "Rationalist Architecture",
  "Rationalist Interior Design",
  "Renaissance Architecture",
  "Retro Interior Design",
  "Riad Architecture",
  "Rococo Architecture",
  "Rococo Interior Design",
  "Rome Architecture",
  "Rumah Gadang Architecture",
  "Rustic Interior Design",
  "Scandinavian Architecture",
  "Scandin"
]

export const movies = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "The Godfather Part II",
  "12 Angry Men",
  "Schindler's List",
  "The Lord of the Rings: The Return of the King",
  "Pulp Fiction",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Good, the Bad and the Ugly",
  "Forrest Gump",
  "Fight Club",
  "The Lord of the Rings: The Two Towers",
  "Inception",
  "Star Wars: Episode V - The Empire Strikes Back",
  "The Matrix",
  "Goodfellas",
  "One Flew Over the Cuckoo's Nest",
  "Se7en",
  "It's a Wonderful Life",
  "Seven Samurai",
  "The Silence of the Lambs",
  "Saving Private Ryan",
  "City of God",
  "Interstellar",
  "Life Is Beautiful",
  "The Green Mile",
  "Star Wars: Episode IV - A New Hope",
  "Terminator 2: Judgment Day",
  "Back to the Future",
  "Spirited Away",
  "The Pianist",
  "Psycho",
  "Parasite",
  "Léon: The Professional",
  "Gladiator",
  "The Lion King",
  "American History X",
  "The Departed",
  "Whiplash",
  "The Prestige",
  "The Usual Suspects",
  "Casablanca",
  "Grave of the Fireflies",
  "Harakiri",
  "The Intouchables",
  "Modern Times",
  "Once Upon a Time in the West",
  "Cinema Paradiso",
  "Rear Window",
  "Alien",
  "City Lights",
  "Apocalypse Now",
  "Memento",
  "Django Unchained",
  "Indiana Jones and the Raiders of the Lost Ark",
  "WALL·E",
  "The Lives of Others",
  "Sunset Blvd.",
  "Paths of Glory",
  "The Shining",
  "The Great Dictator",
  "Avengers: Infinity War",
  "Witness for the Prosecution",
  "Aliens",
  "Spider-Man: Into the Spider-Verse",
  "American Beauty",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  "The Dark Knight Rises",
  "Inglourious Basterds",
  "Oldboy",
  "Amadeus",
  "Coco",
  "Toy Story",
  "Braveheart",
  "Joker",
  "Das Boot",
  "Avengers: Endgame",
  "Princess Mononoke",
  "Good Will Hunting"
];


export const palettes = [
  "Colorized",
  "Color Wheel",
  "Hue",
  "Tone",
  "Value",
  "Gradient",
  "Color Blend",
  "False-Color",
  "Vibrance",
  "Vibrant Colors",
  "Vivid",
  "Bright Colors",
  "Light Colors",
  "Dark Colors",
  "Darkened",
  "Neutral",
  "Dingy Colors",
  "Spectrum",
  "Pigment",
  "Variegated",
  "Pure",
  "Purity",
  "Faded Colors",
  "Faded",
  "Autochrome",
  "EnChroma",
  "Happy Colors",
  "Exciting Colors",
  "Gloomy Colors",
  "Single Color",
  "Double Colors",
  "Dual Colors",
  "Triple Colors",
  "Quadruple Colors",
  "Quintuple Colors",
  "Hextuple Colors",
  "Septuple Colors",
  "Octuple Colors",
  "Infinituple Colors",
  "Palette",
  "Color Palette",
  "Warm Color Palette",
  "Cool Color Palette",
  "Inverted Colors",
  "Colorful",
  "Multicolored",
  "Rainbow",
  "Spectral Color",
  "Vibrant",
  "Chroma",
  "Dichromatism",
  "Tetrachromacy",
  "Saturated",
  "High Saturation",
  "Low Saturation",
  "Neon",
  "Electric Colors",
  "Complimentary-Colors",
  "Split-Complementary-Colors",
  "Supplementary-Colors",
  "Analogous-Colors",
  "Triadic-Colors",
  "Tetradic-Colors",
  "Polychromatic-Colors",
  "Tonal Colors",
  "Light",
  "Light Mode",
  "Dark",
  "Dark Mode",
  "Tones of Black",
  "Tones of Black in Background",
  "Light Blue Background",
  "Light Blue Foreground",
  "Monochromatic",
  "Monochrome",
  "Black and White",
  "Grayscale",
  "Desaturated",
  "Sepia",
  "Cyanopsia",
  "Chloropsia",
  "Erythropsia",
  "Dyschromatopsia",
  "Chromatopsia",
  "Hyperchromatopsia",
  "Contrast",
  "High Contrast",
  "Low Contrast",
  "Color Model",
  "RGB",
  "scRGB",
  "CMYK",
  "HSV",
  "HSL",
  "HCL",
  "VGA",
  "EGA",
  "CGA",
  "HDR",
  "sRGB",
  "DCI-P3",
  "Adobe RGB",
  "ProPhoto RGB",
  "Pantone",
  "YCbCr",
  "YPbPr",
  "Coloroid",
  "Technicolor",
  "Kinemacolor",
  "Kodachrome",
  "Cinecolor",
  "Agfacolor"
];


export const emojis = [
  "😊",
  "👻",
  "💀",
  "🤖",
  "👽",
  "👾",
  "🎃",
  "👍",
  "🤳",
  "🧑",
  "👚",
  "👑",
  "💍",
  "🌲",
  "🐱",
  "🐶",
  "🐼",
  "🐺",
  "🦄",
  "🍄",
  "🐚",
  "🕸",
  "🔥",
  "🌈",
  "🌪",
  "🌀",
  "💧",
  "🌊",
  "🌫",
  "☄",
  "🌌",
  "🪐",
  "🌠",
  "☄️",
  "⭐️",
  "🌟",
  "🍕",
  "🍎",
  "🍏",
  "🍌",
  "🍒",
  "🍉",
  "🥝",
  "🥥",
  "🌶",
  "🥨",
  "✈️",
  "🎪",
  "🛕",
  "⛩",
  "🕋",
  "🎷",
  "💿",
  "📀",
  "⌛️",
  "⏳",
  "💡",
  "⚙️",
  "🔩",
  "🧱",
  "💎",
  "💣",
  "🧨",
  "🎆",
  "🎇",
  "🧪",
  "⚗️",
  "🧬",
  "🧫",
  "🦠",
  "🚽",
  "🧻",
  "🖼",
  "🎈",
  "🎉",
  "🎊",
  "🎨",
  "🎬",
  "🎲",
  "🧩",
  "♟",
  "🎮",
  "🏆",
  "☯️",
  "☮️",
  "♾",
  "⚛️",
  "✨",
  "⚡️",
  "💫",
  "💥",
  "⚠️",
  "☢️",
  "☣️",
  "💠",
  "⚜️",
  "🎵",
  "🎶",
  "🎼",
  "〰️",
  "➰",
  "➿",
  "♠️",
  "♥️",
  "♣️",
  "♦️",  "🍔",
  "🍟",
  "🍕",
  "🌭",
  "🌮",
  "🌯",
  "🍿",
  "🥐",
  "🥞",
  "🍩",
  "🍪",
  "🍦",
  "🍫",
  "🍬",
  "🍭",
  "🍷",
  "🍺",
  "🍸",
  "🍹",
  "☕️",
  "🍽️",
  "🍴",
  "🎂",
  "🍰",
  "🥧",
  "🍓",
  "🍇",
  "🍉",
  "🍍",
  "🍌",
  "🥥",
  "🥑",
  "🥦",
  "🍆",
  "🥕",
  "🌽",
  "🥔",
  "🥒",
  "🍄",
  "🥜",
  "🌰",
  "🍞",
  "🧀",
  "🥩",
  "🍗",
  "🍖",
  "🍤",
  "🍣",
  "🍱",
  "🍙",
  "🍚",
  "🍛",
  "🍜",
  "🍝",
  "🍠",
  "🍢",
  "🍣",
  "🍦",
  "🍡",
  "🍧",
  "🍨",
  "🍩",
  "🍪",
  "🎂",
  "🍰",
  "🥧",
  "🍫",
  "🍬",
  "🍭",
  "🍮",
  "🍯",
  "🍼"
  
]


export const outfits = [
  "Academia Outfit",
  "Androgynous Outfit",
  "Ankara Outfit",
  "Aristocrat Outfit",
  "Athleisure Outfit",
  "Aztec Outfit",
  "Baddie Outfit",
  "Balletcore Outfit",
  "Beach Outfit",
  "Biker Outfit",
  "Bohemian Outfit",
  "Boho Outfit",
  "Bollywood Outfit",
  "Bon Chic Bon Genre Outfit",
  "Bosozoku Outfit",
  "Business Casual Outfit",
  "Casual Outfit",
  "Celtic Outfit",
  "Chav Outfit",
  "Chic Style Outfit",
  "Classit Outfit",
  "Coastal Grandmother Outfit",
  "Cosplay Outfit",
  "Cottagecore Outfit",
  "Cowboy Outfit",
  "Cowgirl Outfit",
  "Dandy Outfit",
  "Decora Kei Outfit",
  "Diesel Punk Outfit",
  "Disco Outfit",
  "Eclectic Outfit",
  "Elegant Outfit",
  "Emo Outfit",
  "Empire Sihouette Outfit",
  "Equestrian Outfit",
  "Ethnic Outfit",
  "Exotic Outfit",
  "Flamboyant Outfit",
  "Flapper Outfit",
  "Folkloric Outfit",
  "Formal Outfit",
  "Gangster Outfit",
  "Garconne Outfit",
  "Girl Next Door Outfit",
  "Girly Outfit",
  "Glamour Outfit",
  "Gothic Outfit",
  "Grunge Outfit",
  "Harajuku Outfit",
  "Haute Couture Outfit",
  "Heavy Metal Outfit",
  "Hippie Outfit",
  "Hipster Outfit",
  "Indie Outfit",
  "Ivy League Outfit",
  "Kampala Blend Outfit",
  "Kawaii Outfit",
  "Kimono Outfit",
  "Kitsch Outfit",
  "Ladylike Outfit",
  "Lagenlook Outfit",
  "Latino Outfit",
  "Light Academia Outfit",
  "Macabre Outfit",
  "Maternity Outfit",
  "Military Outfit",
  "Minimal Outfit",
  "Minimalist Outfit",
  "Modest Outfit",
  "Nautical Outfit",
  "Nerd Outfit",
  "Normcore Outfit",
  "Nugoth Outfit",
  "Parisian Outfit",
  "Peasant Outfit",
  "Pop Outfit",
  "Poppunk Outfit",
  "Posh Outfit",
  "Prairie Outfit",
  "Psychobilly Outfit",
  "Punk Outfit",
  "Punk Rock Outfit",
  "Rasta Outfit",
  "Retro Outfit",
  "Rocker Outfit",
  "Rustic Outfit",
  "Sapeurs Outfit",
  "Scandi Outfit",
  "Scandinavian Outfit",
  "Seapunk Outfit",
  "Shabby Chic Outfit",
  "Ska Outfit",
  "Skate Outfit",
  "Softboys Outfit",
  "Solarpunk Outfit",
  "Southwestern Outfit",
  "Sportswear Outfit",
  "Sporty Outfit",
  "Streetwear Outfit",
  "Summer Outfit",
  "Surf Skate Outfit",
  "Swimwear Outfit",
  "Techno Outfit",
  "Tiki Goth",
  "Tomboy Outfit",
  "Tribal Outfit",
  "Tropical Outfit",
  "Ulzzang Outfit",
  "Urban Outfit",
  "Utility Outfit",
  "Vaporwave Outfit",
  "Varsity Outfit",
  "Vibrant Outfit",
  "Victorian Outfit",
  "Vintage Outfit",
  "Visual Kei Outfit",
  "Vsco Outfit",
  "Wild West Outfit",
  "Witchy Outfit",
  "Y2K Outfit",
  "Zen Outfit",
  "Artistic Outfit",
  "Glam Rock Outfit",
  "Gardening Outfit",
  "Vintage Boho Outfit",
  "Futuristic Outfit",
  "Retro Futurism Outfit",
  "Cottage Chic Outfit",
  "Cyberpunk Outfit",
  "Gothic Lolita Outfit",
  "Vintage Grunge Outfit",
  "Sci-Fi Outfit",
  "Gypsy Outfit",
  "Pirate Outfit",
  "Street Goth Outfit",
  "Art Deco Outfit",
  "Nature-inspired Outfit",
  "Hip Hop Outfit",
  "Vintage Glam Outfit",
  "Steampunk Outfit",
  "Retro Chic Outfit",
  "Geek Chic Outfit",
  "Rockabilly Outfit",
  "Cosmic Outfit",
  "Ethical Fashion Outfit",
  "Geometric Outfit",
  "Casual Chic Outfit",
  "Rustic Boho Outfit",
  "Glam Punk Outfit",
  "Artistic Bohemian Outfit",
  "Vintage Military Outfit",
  "Cybergoth Outfit",
  "Goddess-inspired Outfit",
  "Tropical Chic Outfit",
  "Industrial Chic Outfit",
  "Vintage Country Outfit",
  "Festival Boho Outfit",
  "Sporty Chic Outfit",
  "Vintage Preppy Outfit",
  "Fairy Tale Outfit",
  "Vintage Western Outfit",
  "Futuristic Sportswear Outfit",
  "Romantic Victorian Outfit",
  "Tropical Vacation Outfit",
  "Vintage Rave Outfit",
  "Glamorous Safari Outfit",
  "Cyber Chic Outfit",
  "Vintage Rock Outfit"
];

export const background = [
  'A Stone Route To The Moon', 'Airport', 'Arctic Background', 'Bay Background', 'Beach Background', 'Bedroom',
  'Cemetery Background', 'City Background', 'City Hall', 'Classroom', 'Constantinople', 'Dancing Hall',
  'Desert Background', 'Flower Field Background', 'Football Court', 'Forest Background', 'Gallery Background',
  'Garden Background', 'Gym', 'Heaven Background', 'Hell', 'Home Office Background', 'Hospital Hall',
  'In A Church Background', 'Inside The Castle', 'Jail', 'Kitchen', 'Library Background', 'Living Room',
  'Mountain', 'Music Stage', 'Neon City', 'New York Street Background', 'Northern Lights Background', 'Office',
  'On The Train Background', 'Opera Hall', 'Park', 'Rain Background', 'Restaurant', 'Restaurant Kitchen',
  'River Background', 'School', 'Snow Landscape', 'Subway', 'Tunnel', 'Valley Background', 'Waterfall',
  'White Winter Forest Background', 'Amusement Park', 'Ancient Ruins', 'Aquarium', 'Bamboo Forest', 'Carnival', 'Castle Interior', 'Countryside',
    'Data Center', 'Enchanted Forest', 'Film Studio', 'Haunted Mansion', 'Ice Cave', 'Moonlit Lake', 'Night Market',
    'Ocean Floor', 'Pirate Ship', 'Race Track', 'Space Station', 'Steampunk City', 'Underwater Cave', 'Volcano',
    'Witch Cottage', 'Zen Garden',  'Amusement Park at Night', 'Autumn Forest', 'Breezy Meadow', 'Circus Tent', 'Deep Space', 'Enchanted Castle',
    'Futuristic Cityscape', 'Glowing Caves', 'Hidden Waterfall', 'Jungle Canopy', 'Lunar Landscape', 'Magical Library',
    'Mystic Underwater Realm', 'Night Sky with Aurora', 'Secret Garden', 'Skyline Rooftops', 'Spooky Graveyard',
    'Starship Bridge', 'Sunset Pier', 'Tropical Island Retreat', 'Underground Bunker', 'Victorian Parlor',
    'Winter Wonderland', 'Zen Retreat'
  ];

  export const characters = [
    'Absent Minded Professor', 'African', 'African American', 'Alien', 'Anarchist', 'Asian', 'Astronaut', 'Baby',
    'Black Woman', 'Blind Seer', 'Businessman', 'Carpenter', 'Cartographer', 'Chinese', 'Clown', 'Cowboy', 'Crone',
    'Dark Lord', 'Devil', 'Dracula', 'Dragon Lady', 'Dumb Blonde', 'Evil', 'Evil Clown', 'Fairy', 'Femme Fatale',
    'Filipina', 'French Maid', 'Gamer', 'Geek', 'Geisha', 'Ghost', 'Girl Next Door', 'Goblin', 'God', 'Goddess',
    'Goth', 'Goth Punk', 'Hag', 'Hipster', 'Hispanic', 'Housewife', 'Indigenous', 'Journalist', 'Kid',
    'Lab Technician', 'Mad Scientist', 'Medusa', 'Mermaid', 'Mother Nature', 'Muse', 'Mythological King', 'Nerd',
    'Ninja', 'Nun', 'Occult Detective', 'Painter', 'Patriarch', 'Pierrot', 'Pirate', 'Police Officer', 'Politician',
    'Priest', 'Priestess', 'Professor', 'Queen', 'Quincy Punk', 'Redneck', 'Robot', 'Samurai', 'Secretary', 'Sniper',
    'Soldier', 'Spellcaster', 'Spy', 'Student', 'Superhero', 'Swordman', 'Teen', 'Toddler', 'Tomboy', 'Vamp',
    'Vampire', 'Warrior', 'Werewolf', 'White Woman', 'Witch', 'Wizard', 'Yuppie', 'Zombie',   'Arcane Sorcerer', 'Bounty Hunter', 'Circus Acrobat', 'Cyberpunk Hacker', 'Fashion Model', 'Fire Dancer',
    'Fortune Teller', 'Gang Leader', 'Hippie Musician', 'Ice Queen', 'Lumberjack', 'Magician Assistant',
    'Martial Arts Master', 'Motorcycle Rider', 'Photographer', 'Pirate Captain', 'Racing Driver',
    'Robotics Engineer', 'Rockstar', 'Steampunk Inventor', 'Street Artist', 'Time Traveler', 'Undercover Spy',
    'Vigilante', 'Zombie Slayer', 'Steampunk Inventor', 'Street Artist', 'Time Traveler', 'Unicorn Rider',
    'Vigilante', 'Witch Doctor', 'Xenobiologist', 'Yoga Instructor', 'Zookeeper'
  ];
  
  
